.TH GEOTOAD 1
.SH NAME
geotoad \- geocaching query tool
.SH SYNOPSIS
.TP
.B geotoad
 will invoke text user interface (TUI)
.TP
.B geotoad \fI[options]\fR \fB[--]\fR \fI<search>\fR
 (command-line version)
.SH NOTE
If GeoToad was not installed from a (distribution-specific) package
(like .rpm for RedHat, OpenSuse, CentOS and derivatives; .deb for Debian
and Ubuntu, etc.), it may be necessary to invoke GeoToad with the
.B .rb
suffix, as in \fBgeotoad.rb\fR, \fB./geotoad.rb\fR, \fBruby geotoad.rb\fR
or even \fBruby1.9.3 geotoad.rb\fR
(if the \fBruby\fR in your PATH is not the one you want to use).
'
'In a Windows environment, when not using the installer, create a desktop
'link - using a terminal is highly recommended.
.SH DESCRIPTION
GeoToad is software to help speed up the boring part of geocaching:
choosing the cache and collecting the data. GeoToad lets you perform
queries against the Geocaching website, and export the matching geocaches
to numerous devices and over 20 file formats.
.P
If run without any parameters,
.B geotoad
will launch the interactive mode ("text user interface", "TUI").
It can also be used in command-line mode for specific queries.
.PP
Where multiple entries are possible (e.g. for cache sizes, owners, etc.,
marked by \fB(MULTI)\fR below),
they can be delimited by a pipe symbol (\fB|\fR) or a colon (\fB:\fR),
or you can define your own delimiter(s).
Make sure the pipe symbols are properly escaped from the command shell!
.PP
\fB(USERFILE)\fR - if the user name is followed by an "equal" sign and a filename
(as in \fIusername\fR\fB=\fR\fIfilename\fR),
instead of querying the server the first column of the file is interpreted as
GCxxxxx cache IDs.
\fBWarning:\fR Since colons are used as default \fB(MULTI)\fR delimiters,
if you want to use a file from another (Windows) drive, or with a filename
containing a colon for another reason, you will have to define your own
delimiter (set) - see the \fB-m\fR option for that.
.SH OPTIONS
Option keywords are case-sensitive, and may be separated from values by whitespace
or an equal sign \fB=\fR.
Options can be unambiguously abbreviated, for example, \fB--password\fR may be written
as \fB--pas\fR (but not \fB--p\fR).
.TP
\fB-h\fR|\fB--help\fR
get a short command-line option summary
.TP
\fB-v\fR|\fB--verbose\fR|\fB--debug\fR
enable debugging output - very helpful in case of malfunctions.
.TP
\fB-u\fR|\fB--user\fR|\fB--username\fR \fIusername\fR
geocaching.com username (required)
.TP
\fB-p\fR|\fB--password\fR \fIpassword\fR
geocaching.com password (required)
.TP
\fB-m\fR|\fB--delimiter\fR \fIdelimiter(s)\fR
delimiter(s) to be used for \fB(MULTI)\fR input, default "|:"

The TUI uses "|".
You may try "^" to avoid delimiters that have to be "escaped" ("quoted").
.TP
\fB-o\fR|\fB--output\fR \fIfilename\fR
(first) output file name (default: created from query argument(s) and options)

In case of multiple output formats, subsequent file names are derived from this one.
.TP
\fB-x\fR|\fB--format\fR \fIformat\fR
\fB(MULTI)\fR
output format type(s) (default: gpx)
.TP
\fB-q\fR|\fB--queryType\fR \fI[location|coord|user|owner|country|state|keyword|wid|guid]\fR
query type (default: location)

\fIlocation\fR will use the Google Maps API to translate into coordinates.
Use \fIcoord\fR if you already have coordinates.

\fIcountry\fR and \fIstate\fR queries require a numerical id which the TUI may tell you.
.TP
\fB-s\fR|\fB--sizeMin\fR|\fB--minSize\fR \fI[virtual|not_chosen|other|micro|small|regular|large]\fR
set minimum cache size - \fInot_chosen\fR is equivalent to \fIvirtual\fR
.TP
\fB-S\fR|\fB--sizeMax\fR|\fB--maxSize\fR \fI[virtual|not_chosen|other|micro|small|regular|large]\fR
set maximum cache size
.TP
\fB-c\fR|\fB--cacheType\fR|\fB--type\fR \fI[traditional|multicache|letterbox|event|unknown|cito|virtual|webcam|earthcache|wherigo|...]\fR
\fB(MULTI)\fR
set cache type(s)

If only one type is selected, search will be sped up considerably
by reducing the number of queries sent to the server.
.TP
\fB-d\fR|\fB--difficultyMin\fR|\fB--minDiff\fR \fI1.0-5.0\fR
set minimum difficulty
.TP
\fB-D\fR|\fB--difficultyMax\fR|\fB--maxDiff\fR \fI1.0-5.0\fR
set maximum difficulty
.TP
\fB-t\fR|\fB--terrainMin\fR|\fB--minTerrain\fR \fI1.0-5.0\fR
set minimum terrain
.TP
\fB-T\fR|\fB--terrainMax\fR|\fB--maxTerrain\fR \fI1.0-5.0\fR
set maximum terrain
.TP
\fB-g\fR|\fB--favFactorMin\fR|\fB-minFav\fR \fI0.0-5.0\fR
set minimum fav factor
.TP
\fB-G\fR|\fB--favFactorMax\fR|\fB-maxFav\fR \fI0.0-5.0\fR
set maximum fav factor
.TP
\fB-y\fR|\fB--distanceMax\fR|\fB--radius\fR \fI0.01-500[km]\fR
distance maximum in miles or km (default: 10mi)
.TP
\fB-k\fR|\fB--titleKeyword\fR \fIkeyword\fR
\fB(MULTI)\fR
title keyword search, exclude if prefixed with \fB!\fR
.TP
\fB-K\fR|\fB--descKeyword \fR \fIkeyword\fR
\fB(MULTI)\fR
description keyword search (slow), exclude if prefixed with \fB!\fR
.TP
\fB-i\fR|\fB--ownerInclude\fR|\fB--by\fR \fIusername\fR
\fB(MULTI)\fR
include caches owned by this person
.TP
\fB-I\fR|\fB--ownerExclude\fR|\fB--notby\fR \fIusername\fR
\fB(MULTI)\fR \fB(USERFILE)\fR
exclude caches owned by this person
.TP
\fB-e\fR|\fB--userInclude\fR|\fB--doneBy\fR \fIusername\fR
\fB(MULTI)\fR
include caches found by this person
.TP
\fB-E\fR|\fB--userExclude\fR|\fB--notdoneBy\fR \fIusername\fR
\fB(MULTI)\fR \fB(USERFILE)\fR
exclude caches found by this person
.TP
\fB-j\fR|\fB--placeDateInclude\fR|\fB--since\fR \fIX\fR
include caches placed in the last \fIX\fR days
.TP
\fB-J\fR|\fB--placeDateExclude\fR|\fB--until\fR \fIX\fR
exclude caches placed in the last \fIX\fR days
.TP
\fB-r\fR|\fB--foundDateInclude\fR \fIX\fR
include caches found in the last \fIX\fR days
.TP
\fB-R\fR|\fB--foundDateExclude\fR \fIX\fR
exclude caches found in the last \fIX\fR days
.TP
\fB-a\fR|\fB--attributeInclude\fR \fIid[-]\fR
\fB(MULTI)\fR
select caches with attribute ID \fIid\fR set to "yes", or to "no" if "-" suffix
.TP
\fB-A\fR|\fB--attributeExclude\fR \fIid[-]\fR
\fB(MULTI)\fR
exclude caches with attribute ID \fIid\fR set to "yes", or to "no" if "-" suffix
.TP
\fB-z\fR|\fB--includeDisabled\fR|\fB--bad\fR
include disabled caches
.TP
\fB-n\fR|\fB--notFound\fR|\fB--virgin\fR
only caches not found yet
.TP
\fB-N\fR|\fB--notFoundByMe\fR|\fB--notme\fR
only caches not yet found by login user
.TP
\fB-b\fR|\fB--travelBug\fR|\fB--trackable\fR
only include caches with travelbugs/trackables
.TP
\fB-w\fR|\fB--waypointLength\fR \fIlength\fR
set EasyName waypoint id length. (default: 0=use WID)

Note: negative values are no longer allowed.
.TP
\fB-L\fR|\fB--limitSearchPages\fR \fIcount\fR
limit number of search pages (0=unlimited)
.TP
\fB-l\fR|\fB--logCount\fR \fIcount\fR
limit number of log entries (default: 10)
.TP
\fB-Y\fR|\fB--noCacheDescriptions\fR
do not fetch nor parse cache descriptions, search only

This will reduce the amount of server requests, but there's no way
to determine cache coordinates, hints, attributes, or descriptions.
.TP
\fB-Z\fR|\fB--preserveCache\fR|\fB--keepOld\fR
do not overwrite existing cache description files in file cache
.TP
\fB-O\fR|\fB--noPMO\fR|\fB--nopmo\fR
exclude Premium Member Only caches
.TP
\fB-Q\fR|\fB--onlyPMO\fR|\fB--pmo\fR
select only Premium Member Only caches

Note that \fB-O\fR and \fB-Q\fR are mutually exclusive!
.TP
\fB-P\fR|\fB--proxy\fR \fIproxy\fR
HTTP proxy server, http://username@password@host:port/
.TP
\fB-M\fR|\fB--myLogs\fR|\fB--getlogs\fR
retrieve "my logs" page containing links to all (cache) logs, and store in cache
.TP
\fB-X\fR|\fB--disableEarlyFilter\fR
emergency switch to disable early filtering by difficulty/terrain/size

This may be required should the representation of those values change again.
Normally you don't want to use this!
.TP
\fB-H\fR|\fB--noHistory\fR
suppress history collection (anonymized command lines and counts)

History data won't leave your computer without your intervention,
but may be useful for user surveys.
.TP
\fB-C\fR|\fB--clearCache\fR|\fB--cleanup\fR
selectively clear browser cache
.TP
\fB-U\fR|\fB--unbufferedOutput\fR
switch output to unbuffered (useful for wrappers)
.SH SPECIAL CASES
If your
\fIsearch\fR
item(s) start with a dash (minus sign), it has to be
"hidden" from the option parser. This, in Unix tradition, is done by
inserting a "double dash"
.B --
between the last option and the search argument(s).

Characters like \fB!\fR and \fB|\fR may have to be "escaped" from the shell.

If
.B user
or
.B owner
names contain special (non-ASCII) characters, and you are using Windows,
you may not be able to login or run a "user" query.
In those cases, you'll have to pre-encode those characters.
.B http://www.utf8-chartable.de/unicode-utf8-table.pl?number=1024
will help you to look up the proper UTF-8 codes.
Prefix each two-digit hex value with a percent sign, for example:
.B (capital_letter_O_with_diaeresis)lscheich
will become
.B %c3%96lscheich
(the TUI will may show strange characters, don't worry about them).

If you're planning to use colons (e.g. for \fB(USERFILE)\fR) on the command line,
you may have a look at the \fB-m\fR option which allows you to redefine the
delimiter set.
.SH ENVIRONMENT
.TP
.B GEO_DIR
If set, GeoToad will put its cache in this directory. If not the cache is
placed in ~/.geotoad/ . Note that it is not secure to set GEO_DIR to point
to a world-writable directory such as /tmp.
.TP
.B LANG
To properly handle special characters (which are not in the ASCII character
set, such as umlauts, etc.) we recommend to set
.B LANG
to
.B en_US.UTF-8
or similar. The syntax depends on the shell you're using:
 
.B setenv LANG en_US.UTF-8
for C-shell derivatives (csh, tcsh)
 
.B LANG=en_US.UTF-8; export LANG
for Bourne and Korn shell (sh, ksh)
 
.B export LANG=en_US.UTF-8
for Bourne Again shell and derivatives (bash, dash)
.TP
There is a known yet unfixed issue with the pre-built Windows executable: To properly find some data files, it must be run from its own installation directory.
.SH OUTPUT FORMATS
\." set indentation to "none", use fixed-width font for format list
.TP 0
.ft CW
 cachemate(=)  cetus(+)      csv           delorme        delorme-nourl 
.ft CW
 dna(+)        easygps       gclist        gcvisits(%)    gpsdrive      
.ft CW
 gpsman(+)     gpspilot(+)   gpspoint      gpspoint2(+)   gpsutil(+)    
.ft CW
 gpx           gpx-gsak      gpx-nuvi      gpx-pa         gpx-wpts      
.ft CW
 holux(+)      html          kml(+)        list           magnav(+)     
.ft CW
 mapsend(+)    mxf           myfindgpx     myfindlist     ozi           
.ft CW
 pcx(+)        poi-nuvi(+)   psp(+)        sms            sms2          
.ft CW
 tab           text          tiger         tmpro(+)       tpg(+)        
.ft CW
 vcf           wp2guid       xmap(+)       yourfindgpx    yourfindlist  
.ft CW
 (+) requires gpsbabel  (=) requires cmconvert  (%) requires iconv in PATH
.\" back to normal font
.ft P

.SH EXAMPLES
.TP
\fBNote:\fR Some of these examples may still no longer work as shown. Please help to fix this; see Issue 284 on GoogleCode.
.TP
.B  geotoad
invokes the text user interface
.TP
.B  geotoad -u user -p password 27513
Why do we need a username and password? In October of 2004, Geocaching.com
began to require a login in order to see the coordinates of a geocache.
Please note: Put quotes around your username if it has any spaces in it.

You've just made a file named gt_27513.gpx containing all the geocaches
nearby the zipcode 27513 (Cary, NC - with a maximum distance of 10 miles)
suitable to be read by almost every GPSr device.
.TP
Here are some more complex examples that you can work with:
.TP
.B  geotoad -u user -p password -y 5 -q coord "N56 44.392, E015 52.780"
searches for caches within 5 miles of the above coordinates
.TP
.B  geotoad -u user -p password 27513:27502:33434
performs a multiple search, and combines the results into a single output.
You can combine searches with a delimiter (default is "|", or ":" - except TUI).
This works for all types, though it's most often used with coordinate searches.
.TP
.B  geotoad -u user -p password -x text -o nc.txt -n -q state 34
Outputs a text file with all of the caches in US state North Carolina that are
virgins (have never been found).

Please note that for state and country queries, the numerical id has to be used.
You may use the TUI to search for the country or state number.

Warning: Querying a whole state can be dangerous and may harm your account!
For example, NC has (as of Oct 2013) more than 24k active caches.
You may want to limit the number of search pages parsed (e.g. using \fB-L 10\fR),
as country and state searches return caches in reverse chronological order
(newest ones first).
.TP
.B  geotoad -u user -p password -x html -o palestine.html -q country 276
Get a HTML representation of all caches in Palestine. (Oct 2013: 7, one of them unfound)
.TP
.B  geotoad -u ... -p ... -t 2.5 -E "helixblue:Sallad" -x gpx -o charlotte.gpx 28272
Get caches in the 10-mile zone of zipcode 28272, with a terrain score of 2.5 or higher, 
which users helixblue and Sallad have not visited.
Outputs a GPX format file, which is usable by most GPSr's and other devices.
.TP
.B  geotoad -u ... -p ... -t 2.5 -E anyname=/path/to/file -x gpx -o charlotte.gpx 28272
As before, but read a list of GCxxxx cache IDs from a file instead of querying the server
for found caches.
.TP
.B  geotoad -u ... -p ... -b -K 'stream|creek|lake|river|ocean' -x html -o watery.html -q state 15
Gets every cache in Indiana state with trackables that matches those water keywords.
Makes a pretty HTML file out of it.
.TP
.B  geotoad -u ... -p ... -x gpx -o mylocal.gpx -z -y 1.75 -T 4 -q coord "N 51 23.456 E 012 34.567"
Create a GPX file with all caches around the given location,
max. 1.75 miles away, terrain rating below or equal 4, including disabled ones.
.TP
.B  geotoad -u ... -p ... -m '^+|' -o output.gpx -x "gpx+list|html" -y 2km -q coord "52.25,6.075^53.1,-7.2"
Perform a search around two travel stops with a 2 kilometre radius, 
create three files output.gpx, output.lst, output.html combining the results.
(Note the usage of the \fB-m\fR option to modify the set of delimiters.
As the \fB|\fR character has a special meaning, it must be "quoted".)
.TP
.B  geotoad -u ... -p ... -c multicache -a 6 -A 57 -o family.gpx -x gpx:list -y 25km -q coord "52.25,6.075"
Prepare for a Sunday afternoon walk, and find all multi-caches around
which pretend to be "Kid friendly" (attribute 6) and shorter than 10km (attribute 57).
.TP
.B  geotoad -u ... -p ... -z -q owner -- -aBcDe-
Find all caches created by one owner, even the disabled or archived ones.
Note that the argument has to be separated by \fB--\fR from the rest of the command line.

.SH AUTHOR
Thomas Stromberg and The GeoToad Project
