# -*- encoding : utf-8 -*-

module ReplaceWords

$ReplaceWords = {
    'KILOMETER' => 'km',
    'KILOMETERS' => 'km',
    'KILOMETRES' => 'km',
    'METER'     => 'm',
    'METERS'    => 'm',
    'METRES'    => 'm',
    'MILE'      => 'mi',
    'MILES'     => 'mi',

    'CACHE'     => 'C',
    'GEOCACHE'  => 'GC',
    'GEOC'      => 'GC',
    'GEOCACHING' => 'GCing',
    'NIGHTCACHE' => 'NC',
    'NIGHTC'    => 'NC',

    'A'         => '',
    'AN'        => '',
    'THE'       => '',
    'AND'       => '+',
    'OR'        => '|',
#   'EITHER'    => 'E',
    'ON'        => '',
    'OF'        => '',
    'FROM'      => '',
    'BY'        => '',
    'FOR'       => '',
    'IS'        => '',
    'IN'        => '',
    'WITH'      => 'W/',
#    'THAT'      => 'T',

    'PARK'      => 'Pk',
    'LAKE'      => 'Lk',
    'ROAD'      => 'Rd',
    'RIVER'     => '',
    'CREEK'     => 'Ck',
    'LOOP'      => 'Lp',
    'TRAIL'     => 'Tr',
    'HEAD'      => 'Hd',
    'MOUNTAIN'  => 'Mt',
    'MOUNT'     => 'Mt',
    'COUNTY'    => 'Cty',
    'OVERLOOK'  => 'Ovlk',
    'RIDGE'     => 'Rdg',
    'FOREST'    => 'Frst',
    'POINT'     => 'Pt',
    'HOTEL'     => 'Ht',
    'MOTEL'     => 'Mo',
    'CHURCH'    => 'Ch',
    'CHAPEL'    => 'Chp',
    'STATION'   => 'St',
    'FINAL'     => 'Fi',

    'MISSION'   => 'Msn',
    'IMPOSSIBLE' => 'Imp',
    'DOUBLE'    => 'Dbl',
    'TRIPLE'    => 'Tri',
    'LITTLE'    => 'Lil',
    'SMALL'     => 'Sml',
    'LARGE'     => 'Lrg',
    'BLACK'     => 'Blk',

    'ONE'       => '1',
    'TWO'       => '2',
    'THREE'     => '3',
    'FOUR'      => '4',
    'FIVE'      => '5',
    'SIX'       => '6',
    'SEVEN'     => '7',
    'EIGHT'     => '8',
    'NINE'      => '9',
    'TEN'       => '10',

    'YEARS'     => 'yr',
    'YEAR'      => 'yr',
    'JANUARY'   => 'Jan',
    'FEBRUARY'  => 'Feb',
    'MARCH'     => 'Mar',
    'APRIL'     => 'Apr',
    'JUNE'      => 'Jun',
    'JULY'      => 'Jul',
    'AUGUST'    => 'Aug',
    'SEPTEMBER' => 'Sep',
    'OCTOBER'   => 'Oct',
    'NOVEMBER'  => 'Nov',
    'DECEMBER'  => 'Dec',

    # German Words Follow
    'NACHTCACHE' => 'NC',
    'NACHTC'    => 'NC',

    'DER'       => '',
    'DIE'       => '',
    'DAS'       => '',
    'DEN'       => '',
    'DEM'       => '',
    'DES'       => '',
#   'AN'        => '',
    'AM'        => '',
    'ZU'        => 'Z',
    'ZUM'       => 'Z',
    'ZUR'       => 'Z',
#   'IN'        => '',
    'IM'        => '',
    'INS'       => '',
    'VON'       => '',
    'VOM'       => '',
    'BEI'       => '',
    'BEIM'      => '',
    'FÜR'       => '',
    'AUS'       => '',
    'AUF'       => '',
    'UM'        => '',
    'MIT'       => 'M',
    'BIS'       => '',
    'ZWISCHEN'  => 'Zw',
    'ÜBER'      => '',
    'UEBER'     => '',
    'OBERHALB'  => '',
    'UNTER'     => '',
    'UNTERHALB' => '',
    'OBEN'      => '',
    'UNTEN'     => '',
    'UND'       => '+',
    'ODER'      => '/',
    'ABER'      => '',

    'KIRCHE'    => 'Ki',
    'PLATZ'     => 'Pl',
    'PARKPLATZ' => 'PPl',
    'NATURLEHRPFAD' => 'NLP',
    'BAHNHOF'   => 'Bf',
    'HAUPTBAHNHOF' => 'Hbf',
    'DEUTSCH'   => 'Dt',
    'DEUTSCHE'  => 'Dt',
    'DEUTSCHES' => 'Dt',
    'DEUTSCHER' => 'Dt',
    'KLEIN'     => 'Kl',
    'KLEINE'    => 'Kl',
    'KLEINER'   => 'Kl',
    'KLEINES'   => 'Kl',
    'KLEINEN'   => 'Kl',
    'GROß'      => 'Gr',
    'GROßE'     => 'Gr',
    'GROßER'    => 'Gr',
    'GROßEN'    => 'Gr',
    'NEUE'      => 'N',
    'NEUEN'     => 'N',
    'NEUER'     => 'N',
    'NEUES'     => 'N',
    'RUND'      => 'Ru',
    'RUNDE'     => 'Ru',
    'RUNDGANG'  => 'Rd',
    'TEIL'      => 'Tl',
    'VERSION'   => 'V',
    'VERS'      => 'V',
    'SCHWESTER' => 'Schw',
    'BRUDER'    => 'Br',

    'EIN'       => '1',
    'EINE'      => '1',
    'EINEN'     => '1',
    'EINEM'     => '1',
    'EINER'     => '1',
    'EINES'     => '1',
    'ZWEI'      => '2',
    'DREI'      => '3',
    'VIER'      => '4',
    'FÜNF'      => '5',
    'SECHS'     => '6',
    'SIEBEN'    => '7',
    'ACHT'      => '8',
    'NEUN'      => '9',
    'ZEHN'      => '10',

    'JAHRE'     => 'J',
    'JAHR'      => 'J',
    'JANUAR'    => 'Jan',
    'FEBRUAR'   => 'Feb',
    'MÄRZ'      => 'Mar',
    'JUNI'      => 'Jun',
    'JULI'      => 'Jul',
    'OKTOBER'   => 'Okt',
    'DEZEMBER'  => 'Dez',

  }

end
